-- 접속자 확인
SELECT USER FROM DUAL;

create table MEMBER (
    ID number primary key,
    EMAIL varchar2(255) unique,
    PASSWORD varchar2(100),
    NAME varchar2(100),
    REGDATE date 
);

CREATE SEQUENCE MEMBER_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRI_MEMBER_ID_SEQ
    BEFORE INSERT ON MEMBER FOR EACH ROW 
BEGIN 
    IF Inserting AND :NEW.ID IS NULL THEN 
        SELECT MEMBER_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END; 
